# Generated by Django 5.2.17 on 2026-09-23 21:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('quiz_submit', 'Quiz Completed'), ('ai_question', 'AI Question Asked'), ('scan_question', 'Question Scanned'), ('topic_study', 'Topic Studied'), ('note_view', 'Note Studied')], max_length=50)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Learning Activity',
                'verbose_name_plural': 'Learning Activities',
                'ordering': ['-created_at'],
            },
        ),
    ]
