# Generated by Django 5.2.17 on 2026-09-23 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(blank=True, choices=[('female', 'Female'), ('male', 'Male'), ('other', 'Other')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='longest_streak',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
