# Generated by Django 5.2.17 on 2026-09-10 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('exam_type', models.CharField(choices=[('mid1', 'Mid-Term 1'), ('mid2', 'Mid-Term 2'), ('endsem', 'End Semester'), ('supply', 'Supplementary'), ('model', 'Model Paper')], default='endsem', max_length=20)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='pyqs/papers/')),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_papers', to='academics.subject')),
            ],
            options={
                'ordering': ['-year'],
                'unique_together': {('subject', 'year', 'exam_type')},
            },
        ),
        migrations.CreateModel(
            name='PYQQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(choices=[('long', 'Long Answer (10 marks)'), ('short', 'Short Answer (5 marks)'), ('very_short', 'Very Short Answer (2 marks)'), ('numerical', 'Numerical Problem'), ('mcq', 'Multiple Choice'), ('fill', 'Fill in the Blank')], default='long', max_length=20)),
                ('marks', models.PositiveSmallIntegerField(default=10)),
                ('solution_text', models.TextField(blank=True)),
                ('frequency_count', models.PositiveIntegerField(default=1)),
                ('importance_score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pyq_questions', to='academics.topic')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pyq_questions', to='academics.unit')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='pyqs.questionpaper')),
            ],
            options={
                'ordering': ['-importance_score'],
            },
        ),
    ]
