"""
Gemini AI service for the ErVeda platform.

Features:
1. Syllabus-aware AI responses
2. Student academic context
3. Multi-turn conversations
4. Image-based question scanner (OCR + step-by-step solving)
5. Resilient execution:
   - Primary model: gemini-3.5-flash
   - Fallback model: gemini-3.5-flash-lite (auto-retries on 503 / high demand)
   - Works with google-genai SDK or direct Google REST API (compatible with all Python versions)
"""

import json
import base64
import logging
import urllib.request
import urllib.error
from typing import Optional, List, Dict, Any, Tuple
from django.conf import settings

logger = logging.getLogger(__name__)

# Active Gemini models (3.5-flash is stable, active, and fast)
DEFAULT_MODEL = "gemini-3.5-flash"
GEMINI_MODEL = getattr(settings, "GEMINI_MODEL", DEFAULT_MODEL)
FALLBACK_MODELS = ["gemini-3.5-flash", "gemini-3.5-flash-lite"]


class GeminiRestClient:
    """Lightweight REST-based client for Google Gemini API."""

    def __init__(self, api_key: str):
        self.api_key = api_key

    def generate_content(
        self,
        contents: List[Dict[str, Any]],
        system_instruction: Optional[str] = None,
        models: Optional[List[str]] = None,
        timeout: int = 35
    ) -> Tuple[Optional[str], Optional[str]]:
        """
        Calls Gemini generateContent endpoint with automatic fallback on 503/429/timeouts.
        """
        if models is None:
            models = [GEMINI_MODEL] + [m for m in FALLBACK_MODELS if m != GEMINI_MODEL]

        last_error = None

        for model in models:
            url = (
                f"https://generativelanguage.googleapis.com/v1beta/models/"
                f"{model}:generateContent?key={self.api_key}"
            )
            payload_data: Dict[str, Any] = {"contents": contents}

            if system_instruction:
                payload_data["system_instruction"] = {
                    "parts": [{"text": system_instruction}]
                }

            payload_bytes = json.dumps(payload_data).encode("utf-8")
            req = urllib.request.Request(
                url,
                data=payload_bytes,
                headers={"Content-Type": "application/json"}
            )

            try:
                with urllib.request.urlopen(req, timeout=timeout) as resp:
                    resp_data = json.loads(resp.read().decode("utf-8"))
                    candidates = resp_data.get("candidates", [])
                    if candidates:
                        parts = candidates[0].get("content", {}).get("parts", [])
                        generated_text = "".join(p.get("text", "") for p in parts)
                        return generated_text, None
                    return "", "No response was generated by the model."

            except urllib.error.HTTPError as http_err:
                err_body = http_err.read().decode("utf-8", errors="replace")
                last_error = f"HTTP {http_err.code}: {err_body}"
                logger.warning(
                    f"Gemini model {model} returned HTTP {http_err.code}. Trying fallback."
                )
                if http_err.code in (503, 429, 500, 404):
                    continue
                break

            except Exception as exc:
                last_error = str(exc)
                logger.warning(f"Gemini model {model} failed with: {exc}. Trying fallback.")
                continue

        return None, last_error


def get_gemini_client():
    """
    Initialize and return a client.
    Returns GeminiRestClient or Google GenAI client if available.
    """
    api_key = getattr(settings, "GEMINI_API_KEY", "")
    if not api_key:
        return None

    try:
        from google import genai
        return genai.Client(api_key=api_key)
    except Exception:
        return GeminiRestClient(api_key=api_key)



def build_system_context(student, subject=None, topic=None) -> str:
    """
    Build academic context for the AI.
    This makes ErVeda AI syllabus-aware.
    """

    context_parts = [
        "You are ErVeda AI — an intelligent academic assistant for B.Tech engineering students.",
        "You provide clear, accurate, exam-oriented explanations tailored to the student's syllabus.",
        "",
        "STUDENT ACADEMIC CONTEXT:",
    ]

    if student.university:
        context_parts.append(
            f"- University: {student.university.name} "
            f"({student.university.short_name})"
        )

    if student.regulation:
        context_parts.append(
            f"- Regulation: {student.regulation.name}"
        )

    if student.branch:
        context_parts.append(
            f"- Branch: {student.branch.name} "
            f"({student.branch.short_name})"
        )

    if student.current_year:
        context_parts.append(
            f"- Year: {student.get_current_year_display()}"
        )

    if student.current_semester:
        context_parts.append(
            f"- Semester: {student.current_semester}"
        )

    if subject:
        context_parts.append(
            f"- Current Subject: {subject.name} "
            f"({subject.subject_code})"
        )

    if topic:
        context_parts.append(
            f"- Current Topic: {topic.name}"
        )

    context_parts.extend([
        "",
        "INSTRUCTIONS:",
        "- Provide answers suitable for university exam preparation.",
        "- Structure answers with proper headings, numbered points, and examples.",
        "- For technical questions, include definitions, working, advantages and disadvantages.",
        "- For numericals, show step-by-step solutions with formulas.",
        "- Keep explanations clear enough for a student who may be learning the topic.",
        "- At the end, suggest related topics or PYQ patterns if relevant.",
        "- Respond in English unless the student writes in another language.",
    ])

    return "\n".join(context_parts)


def get_ai_response(
    user_message: str,
    session,
    student,
    subject=None,
    topic=None
) -> dict:
    """
    Get an AI response for a chat message.

    Returns:
        {
            'answer': str,
            'sources': list,
            'error': str | None
        }
    """
    api_key = getattr(settings, "GEMINI_API_KEY", "")
    if not api_key:
        return {
            "answer": (
                "⚠️ AI Assistant is not configured yet.\n\n"
                "Please add your GEMINI_API_KEY to the .env file."
            ),
            "sources": [],
            "error": "no_api_key_or_sdk"
        }

    # ---------------------------------------------------------
    # Build previous conversation history
    # ---------------------------------------------------------
    contents: List[Dict[str, Any]] = []

    if session and hasattr(session, "messages"):
        previous_messages = session.messages.all()[:10]
        for msg in previous_messages:
            role = "user" if msg.role == "user" else "model"
            contents.append({
                "role": role,
                "parts": [{"text": msg.content}]
            })

    # Add current user message
    contents.append({
        "role": "user",
        "parts": [{"text": user_message}]
    })

    system_context = build_system_context(student, subject, topic)

    # ---------------------------------------------------------
    # Call Gemini via resilient REST client
    # ---------------------------------------------------------
    client = GeminiRestClient(api_key=api_key)
    answer, error = client.generate_content(
        contents=contents,
        system_instruction=system_context
    )

    if error:
        return {
            "answer": (
                f"Sorry, I encountered an error: {error}\n\n"
                "Please try asking your question again."
            ),
            "sources": [],
            "error": error
        }

    return {
        "answer": answer or "I couldn't generate an answer. Please try rephrasing.",
        "sources": [],
        "error": None
    }


def solve_question_with_image(
    image_bytes: bytes,
    mime_type: str = "image/jpeg"
) -> dict:
    """
    Use Gemini Vision to read and solve a question from an image.
    Powers the ErVeda Question Scanner.
    """
    api_key = getattr(settings, "GEMINI_API_KEY", "")
    if not api_key:
        msg = "AI is not configured. Please add GEMINI_API_KEY to your .env file."
        return {
            "full_response": msg,
            "solution": msg,
            "question_text": "",
            "topic": "",
            "method": "",
            "error": "no_api_key_or_sdk"
        }

    prompt = (
        "You are an expert engineering tutor. "
        "The student has uploaded an image of a question from an exam or assignment.\n\n"
        "Please perform the following tasks:\n\n"
        "1. Extract the exact question text from the image (OCR).\n"
        "2. Identify the subject and topic (e.g. Mathematics - Differentiation, DBMS - Normalization).\n"
        "3. Solve the question step by step with clear explanations, formulas, and working.\n"
        "4. Provide the final answer clearly.\n\n"
        "Format your response exactly like this:\n\n"
        "**EXTRACTED QUESTION:**\n"
        "[exact question text from image]\n\n"
        "**SUBJECT/TOPIC:**\n"
        "[subject name - topic name]\n\n"
        "**METHOD/APPROACH:**\n"
        "[brief description of the solution method]\n\n"
        "**STEP-BY-STEP SOLUTION:**\n"
        "[numbered steps]\n\n"
        "**FINAL ANSWER:**\n"
        "[clear final answer]\n\n"
        "**RELATED CONCEPTS:**\n"
        "[2-3 related concepts the student should also know]"
    )

    b64_img = base64.b64encode(image_bytes).decode("utf-8")

    contents = [{
        "role": "user",
        "parts": [
            {"text": prompt},
            {
                "inline_data": {
                    "mime_type": mime_type,
                    "data": b64_img
                }
            }
        ]
    }]

    client = GeminiRestClient(api_key=api_key)
    solution_text, error = client.generate_content(
        contents=contents,
        timeout=45
    )

    if error:
        err_msg = f"Error processing image: {error}"
        return {
            "full_response": err_msg,
            "solution": err_msg,
            "question_text": "",
            "topic": "",
            "method": "",
            "error": error
        }

    return {
        "full_response": solution_text or "No solution generated.",
        "solution": solution_text or "No solution generated.",
        "question_text": "",
        "topic": "",
        "method": "",
        "error": None
    }


def generate_ai_text(prompt: str, system_instruction: Optional[str] = None) -> str:
    """
    General helper to generate text for any module (such as quiz feedback).
    """
    api_key = getattr(settings, "GEMINI_API_KEY", "")
    if not api_key:
        return ""

    client = GeminiRestClient(api_key=api_key)
    text, _ = client.generate_content(
        contents=[{"role": "user", "parts": [{"text": prompt}]}],
        system_instruction=system_instruction
    )
    return text or ""