"""
Admin configuration for Quizzes app.
Manages Quiz, QuizQuestion, QuizAttempt, and QuizAnalysis models.
"""

from django.contrib import admin
from .models import Quiz, QuizQuestion, QuizAttempt, QuizAnalysis


# ---------------------------------------------------------------------------
# Inline: Questions inside a Quiz (the primary way to add questions)
# ---------------------------------------------------------------------------
class QuizQuestionInline(admin.TabularInline):
    model = QuizQuestion
    extra = 3
    fields = ('order', 'question_text', 'question_type', 'options',
              'correct_answer', 'explanation', 'marks', 'topic')
    ordering = ('order',)


# ---------------------------------------------------------------------------
# Quiz
# ---------------------------------------------------------------------------
@admin.action(description='Activate selected quizzes (visible to students)')
def activate_quizzes(modeladmin, request, queryset):
    queryset.update(is_active=True)


@admin.action(description='Deactivate selected quizzes (hide from students)')
def deactivate_quizzes(modeladmin, request, queryset):
    queryset.update(is_active=False)


@admin.register(Quiz)
class QuizAdmin(admin.ModelAdmin):
    list_display = (
        'title', 'subject', 'quiz_type', 'difficulty',
        'question_count', 'time_limit_minutes', 'total_marks',
        'is_active', 'created_at',
    )
    list_filter = ('is_active', 'quiz_type', 'difficulty',
                   'subject__semester__branch',
                   'subject__semester__regulation__university')
    search_fields = ('title', 'subject__name', 'subject__subject_code')
    list_editable = ('is_active',)
    ordering = ('-created_at',)
    inlines = [QuizQuestionInline]
    actions = [activate_quizzes, deactivate_quizzes]
    date_hierarchy = 'created_at'

    fieldsets = (
        ('Quiz Info', {
            'fields': ('title', 'quiz_type', 'difficulty'),
        }),
        ('Academic Link', {
            'fields': ('subject', 'unit', 'topic'),
        }),
        ('Settings', {
            'fields': ('time_limit_minutes', 'total_marks', 'pass_marks', 'is_active'),
        }),
    )

    def question_count(self, obj):
        return obj.questions.count()
    question_count.short_description = 'Questions'


# ---------------------------------------------------------------------------
# QuizQuestion (also editable stand-alone)
# ---------------------------------------------------------------------------
@admin.register(QuizQuestion)
class QuizQuestionAdmin(admin.ModelAdmin):
    list_display = ('short_text', 'quiz', 'question_type', 'marks', 'order')
    list_filter = ('question_type', 'quiz__subject__semester__branch')
    search_fields = ('question_text', 'quiz__title')
    ordering = ('quiz', 'order')

    def short_text(self, obj):
        return obj.question_text[:80] + ('…' if len(obj.question_text) > 80 else '')
    short_text.short_description = 'Question'


# ---------------------------------------------------------------------------
# QuizAttempt (read-only — generated by students)
# ---------------------------------------------------------------------------
@admin.register(QuizAttempt)
class QuizAttemptAdmin(admin.ModelAdmin):
    list_display = (
        'student', 'quiz', 'status', 'score',
        'correct_count', 'wrong_count', 'percentage', 'started_at',
    )
    list_filter = ('status', 'quiz__subject__semester__branch')
    search_fields = ('student__username', 'student__email', 'quiz__title')
    readonly_fields = (
        'student', 'quiz', 'status', 'score', 'total_questions',
        'correct_count', 'wrong_count', 'answers',
        'started_at', 'completed_at', 'time_taken_seconds',
    )
    ordering = ('-started_at',)

    def percentage(self, obj):
        return f'{obj.percentage}%'
    percentage.short_description = 'Score %'

    def has_add_permission(self, request):
        return False  # Attempts are created by students

    def has_change_permission(self, request, obj=None):
        return False  # Read-only


# ---------------------------------------------------------------------------
# QuizAnalysis (read-only — generated by AI)
# ---------------------------------------------------------------------------
@admin.register(QuizAnalysis)
class QuizAnalysisAdmin(admin.ModelAdmin):
    list_display = ('attempt', 'created_at')
    readonly_fields = (
        'attempt', 'weak_topics', 'strong_topics',
        'recommendations', 'ai_feedback', 'created_at',
    )
    ordering = ('-created_at',)

    def has_add_permission(self, request):
        return False

    def has_change_permission(self, request, obj=None):
        return False

