# Generated by Django 5.2.17 on 2026-09-29 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='regulation',
            name='branches',
            field=models.ManyToManyField(blank=True, related_name='regulations', to='academics.branch'),
        ),
        migrations.AddField(
            model_name='subject',
            name='ltp',
            field=models.CharField(blank=True, default='3-0-0', help_text='L-T-P format (e.g. 3-0-0)', max_length=20),
        ),
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_type', models.CharField(blank=True, default='Professional Core Course (PCC)', max_length=100)),
                ('course_objectives', models.TextField(blank=True, help_text='Course objectives (markdown or bullet list)')),
                ('course_outcomes', models.TextField(blank=True, help_text='Expected course outcomes after completion')),
                ('textbooks', models.TextField(blank=True, help_text='Prescribed textbooks with authors and editions')),
                ('reference_books', models.TextField(blank=True, help_text='Reference books and materials')),
                ('additional_resources', models.TextField(blank=True, help_text='Web links, NPTEL/Coursera, and tools')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='syllabus', to='academics.subject')),
            ],
            options={
                'verbose_name': 'Syllabus',
                'verbose_name_plural': 'Syllabi',
            },
        ),
        migrations.AddField(
            model_name='unit',
            name='syllabus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='units', to='academics.syllabus'),
        ),
    ]
