# Generated by Django 5.2.17 on 2026-09-29 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_regulation_branches_subject_ltp_syllabus_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='university',
            options={'ordering': ['name'], 'verbose_name': 'University / College', 'verbose_name_plural': 'Universities & Colleges'},
        ),
        migrations.AddField(
            model_name='university',
            name='parent_university',
            field=models.ForeignKey(blank=True, help_text='Parent university if this is an affiliated college/institution (e.g. JNTUH).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affiliated_colleges', to='academics.university'),
        ),
    ]
